### ISSUE TITLE
image controller not fetching new images

### ISSUE THREAD

**Issue by JRDD** [fluxcd/image-reflector-controller#108]
We have docker tags that consist {version}-alpha.{build_number}.{revision_number}
if the revision number starts with 0 and its all numbers. the image-controller will not fetch it as a new image.
ex: 

`0.0.1-alpha.12.b4djgk3 // recognizes as a new image`

new image gets pushed

```
0.0.1-alpha.13.0545458 // does not recognize as a new image
0.0.1-alpha.12.b4djgk3 // fetches fine
```
we try retagging the same image with an "r" in front of the revision number and that helped as a work around

```
0.0.1-alpha.13.r0545458 // recognizes as a new image
0.0.1-alpha.12.b4djgk3 // 
```

**Comment by relu** [comment]
Would you be able to provide the spec of the ImagePolicy you are using?
