### ISSUE TITLE
ImageRepository not populating Last Scan in additionalPrinterColumns

### ISSUE THREAD

**Issue by nomeelnoj** [fluxcd/image-reflector-controller#118]
The additionalPrinterColumn for LAST SCAN is not populating.  I believe it was #56 that introduced this.  I have confirmed that updating the CRD as follows populates the field:

https://github.com/fluxcd/image-reflector-controller/blob/main/config/crd/bases/image.toolkit.fluxcd.io_imagerepositories.yaml#L20

should instead read 
```
.status.lastScanResult.scanTime
```

**Comment by relu** [comment]
Thank you for reporting!
