### ISSUE TITLE
Store image metadata persistently

### ISSUE THREAD

**Issue by squaremo** [fluxcd/image-reflector-controller#12]
The image metadata (tags, for now) used by the image reflector are just kept in a hash, to start with. But given the expense (and latency) of scanning for more image metadata, this will soon be a pain point, because any restart will lose everything.

A couple of design ideas:
 - put it in an SQLite DB on a persistent volume (will it fail over nicely? probably not, but decent as a solution for recovery after crashes)
 - put it in a central database which is set up separately (extra for experts ..)

The one thing memcached was quite useful for, in theory, was expiring entries -- any solution here will probably need a garbage collection process.

**Comment by stefanprodan** [comment]
I propose we use [dgraph-io/badger](https://github.com/dgraph-io/badger) that has ACID and TTL support.

**Comment by squaremo** [comment]
> I propose we use [dgraph-io/badger](https://github.com/dgraph-io/badger) that has ACID and TTL support.

😍 where has this database been all my life

**Comment by squaremo** [comment]
@bigkevmcd Neat! That would be a solid step forward.

Yes, the database interfaces are totally minimal at the minute -- there just as placeholders, really. Feel free to expand those, even if it's just to add an error return value for now.

TTLs in the [v1 implementation](https://github.com/fluxcd/flux/tree/master/pkg/registry/cache) are used as a kind of indirect garbage collection. Latterly, memcached is used more like a database, and the TTL is used just to allow memcached a chance to relieve memory pressure (like "once this entry is out of date, feel free to discard it if you need to"). This is not a design I would happily recapitulate, if I'm honest :-)

In _this_ implementation, the database is straight-forwardly a database, with entries added and removed according to the custom resources in play, and there is no need for garbage collection. There _may_ still be a place for TTL, since there is still a notion of entries being out of date, though it needs to be figured out what consequence an out-of-date entry should have. For now I would leave TTL out.

**Comment by relu** [comment]
@bigkevmcd I'd be interested in taking over the badger integration in case you no longer have the time to tackle it. Not sure if you made any progress on it or not, let's catch up and let me know if I can help with anything if you still want to do it.

**Comment by stefanprodan** [comment]
Implemented in #65
