### ISSUE TITLE
Tag limit on GitHub container repos

### ISSUE THREAD

**Issue by speedst3r** [fluxcd/image-reflector-controller#142]
I am using several images from the linuxserver repositories on ghcr.io, and the image reflector is only returning 1000 tags for them even when there are more than 1000 tags. This is preventing those repositories from matching newer tags and being updated by the automation controller. I configured authentication on one of the repos but the 1000 tag limit is still being hit. 

```
$ flux get image repository tautulli
NAME            READY   MESSAGE                                 LAST SCAN                       SUSPENDED
tautulli        True    successful scan, found 1000 tags        2021-05-08T09:22:11+08:00       False
```

If I use curl on the API tags list URL for tautulli (https://ghcr.io/v2/linuxserver/tautulli/tags/list) I get 1088 tags returned. 

```
$ curl -s -H "Authorization: Bearer $(echo <token> | base64)" https://ghcr.io/v2/linuxserver/tautulli/tags/list | jq '.tags | length'
1088
```

The PHP Docker Hub registry is returning over 5000 tags so it might be something specific to GH.

```
$ flux get image repository php
NAME    READY   MESSAGE                                 LAST SCAN                       SUSPENDED
php     True    successful scan, found 5033 tags        2021-05-08T09:22:03+08:00       False
```

Running image-reflector-controller v0.9.1

**Comment by speedst3r** [comment]
Just realised you might want the repository configuration too

```
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageRepository
metadata:
  name: tautulli
  namespace: flux-system
spec:
  image: ghcr.io/linuxserver/tautulli
  interval: 1h0m0s
  secretRef:
    name: registry-ghcr-speedst3r
```

**Comment by bigkevmcd** [comment]
It looks like it's because https://github.com/google/go-containerregistry/blob/main/pkg/v1/remote/list.go#L52 is limited to 1000

**Comment by kingdonb** [comment]
I see that distribution/distribution#3143 was merged about 15 days ago. Does this mean there can be progress on this issue, or can it be closed? (I think it still blocks on GCHR taking action.)

**Comment by speedst3r** [comment]
It looks like it's resolved, I am seeing over 1000 tags returned for the repositories I have configured.

```
$ flux get image repository tautulli
NAME            READY   MESSAGE                                 LAST SCAN                       SUSPENDED
tautulli        True    successful scan, found 1436 tags        2021-09-24T16:19:18+08:00       False
```
