### ISSUE TITLE
Confusing error message when some of the tags do not match regex properly

### ISSUE THREAD

**Issue by ilya-git** [fluxcd/image-reflector-controller#143]
1. I have an image repository with one tag
    
    SHA-123

And I use this regex `^[a-fA-F0-9]+-(?P<build_number>[0-9]*)`  to find the "123" that is later being compared numerically. 

2. I now add this tag

   SHA-v1.2.3-prod

Now image policy starts failing with the following message:

> no image found for policy

It seems that the real problem is that my Regex does not guarantee only numbers (no $ at the end) so it will read the new tag and numerical policy cannot apparently be applied.

My suggestion is to improve the error message to be more informative as really there are images found for the policy (form step 1), but there are some images that are failing. Ideally the message should include the tag that does not work as well, e.g.

"found image SHA-v1.2.3-prod which extracts <extracted value> that cannot be used in specified policy"

That would help narrow down the problem as the original message is quite confusing: there are in fact images that satisfy the policy.

**Comment by relu** [comment]
Thanks for reporting this, @ilya-git. I'll look into it and see what improvements can be made.
