### ISSUE TITLE
image reflector crashlooping

### ISSUE THREAD

**Issue by durprasa** [fluxcd/image-reflector-controller#168]
I see this crash that is occurring in image reflector probably due to a bad image policy. Should be gracefully handled though?

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x16138f5]

goroutine 531 [running]:
github.com/fluxcd/image-reflector-controller/internal/policy.(*SemVer).Latest(0x0, 0xc014b14000, 0x38, 0x40, 0xc00cf2a4a0, 0x0, 0x0, 0x0)
        /workspace/internal/policy/semver.go:55 +0x135
github.com/fluxcd/image-reflector-controller/controllers.(*ImagePolicyReconciler).Reconcile(0xc00bfb4000, 0x1ba9fb8, 0xc0147f83f0, 0xc00c2b7ab0, 0xb, 0xc00c2b7a90, 0x10, 0xc0147f8300, 0x0, 0x0, ...)
        /workspace/controllers/imagepolicy_controller.go:140 +0x11a9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00bf90e60, 0x1ba9f10, 0xc00b917140, 0x17e5800, 0xc00050ab20)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:298 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00bf90e60, 0x1ba9f10, 0xc00b917140, 0x1a3af00)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:253 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0xc000325350, 0xc00bf90e60, 0x1ba9f10, 0xc00b917140)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:214 +0x6b
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:210 +0x425

**Comment by franitel** [comment]
Hi we have the same issue:

![image](https://user-images.githubusercontent.com/45692517/133624035-929baade-8761-4a07-971c-bce7cf260dba.png)

E0916 13:48:01.857168       6 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)

Infraestructure:
k8s: 1.19.9
ghcr.io/fluxcd/image-reflector-controller:v0.9.1
ghcr.io/fluxcd/image-automation-controller:v0.9.1

we have some services on production using this option to deploy our services and now we need to do manually.
Please let me know if you need more details or if I can help in anything to this this issue.

BR,
Francisco Rodriguez.

Note for StefanProdan:
stefanprodan

Just comment that I have been following your work for a long time and you do a very good job, thank you for that!!

**Comment by pjbgf** [comment]
Closing this issue assuming that it was fixed by #172 - released on `v0.12.0`. 
If this isn't the case, please just comment here and I will be more than happy to reopen it again.
