### ISSUE TITLE
Suspend / Force scanning

### ISSUE THREAD

**Issue by squaremo** [fluxcd/image-reflector-controller#19]
The general pattern within GitOps Toolkit is that resources can be suspended (don't act on it), and those running on a schedule can be run on demand (act on it now). See, for example, https://toolkit.fluxcd.io/components/kustomize/kustomization/#reconciliation

This applies at least to ImageRepository. I don't think it applies to ImagePolicy, since it just reflects a calculation, rather than an ongoing process.

**Comment by bigkevmcd** [comment]
For the second part (force-scan) I wonder if it wouldn't be useful to extract the [predicate](https://github.com/fluxcd/source-controller/blob/master/controllers/predicate.go) and annotation to be shared across services?

**Comment by squaremo** [comment]
> For the second part (force-scan) I wonder if it wouldn't be useful to extract the [predicate](https://github.com/fluxcd/source-controller/blob/master/controllers/predicate.go) and annotation to be shared across services?

Yeah I think that's a good idea. There will probably still need to be code for deciding whether to do a scan, or if not, when to requeue. But it's a good habit to get into with the controllers, and will avoid some needless reconcile calls no doubt.

Side note: I initially didn't grok how scheduling via `RequeueAfter` would work with the filter. For the benefit of people as slow to catch on as I am, the predicate only pertains to the changes coming _into_ the queue, and the scheduling works by requeuing directly.
