### ISSUE TITLE
Container Registry on 5005 port

### ISSUE THREAD

**Issue by lczerepuk** [fluxcd/image-reflector-controller#220]
Hello,

I have deployed **image-reflector-controller** with version: **ghcr.io/fluxcd/image-reflector-controller:v0.15.0**
When I want to create ImageRepository with port 5005, eg. git.mydomain.com:5005/foo/bar I got message:

`
✗ .spec.image value should not start with URL scheme; remove 'git.mydomain.com://'
`

How to fix this? 

Ps. Version v0.14.0 works fine.

**Comment by shanedabes** [comment]
I'm trying to run the automatic image update also with a private repository on a non-standard port, facing the same issue.

**Comment by kingdonb** [comment]
There is a resolution for this issue in process of being merged, see #222 👍

**Comment by lczerepuk** [comment]
When can I expect new version release with this fix ?

**Comment by stefanprodan** [comment]
This week we'll release flux 0.26 that will include this fix, you can subscribe to this issue https://github.com/fluxcd/flux2/issues/2308
