### ISSUE TITLE
Image Repository

### ISSUE THREAD

**Issue by vipulJain05** [fluxcd/image-reflector-controller#257]
Is it possible to provide a dynamic image name or region in the image repository with AWS ECR?
For example: 0000.dkr.ecr.{aws-region}.amazonaws.com/repo

**Comment by stefanprodan** [comment]
Yes you can use Flux variable substitutions, you would create a ConfigMap with your cluster info (cluster name, region, zone, etc) then use substituteFrom in the Flux Kustomization that applies the image repositories, in the repository spec you can use the variables declared in the ConfigMap. Docs here: https://fluxcd.io/docs/components/kustomize/kustomization/#variable-substitution

**Comment by kingdonb** [comment]
Please let us know if this did not solve your issue! Thanks

(Closing)
