### ISSUE TITLE
Extract auto-login code to fluxcd/pkg

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/image-reflector-controller#264]
As described in the RFC [Flux OCI support for Kubernetes manifests](https://github.com/fluxcd/flux2/pull/2601), source-controller will have to use the same flags and authentication logic for Azure, AWS and Google Cloud as implemented in this controller. 

We need to extract the auto-login code and the flags: `--aws-autologin-for-ecr`, `--azure-autologin-for-acr`, `--gcp-autologin-for-gcr` to a dedicated package in `fluxcd/pkg/oci/auth` so that we can share the code between image-reflector-controller and source-controller.

**Comment by withnale** [comment]
I was searching for this issue on the source-controller but have found it here. Is there an eta on this?

The workload-identity logic works well in image-reflector, but I assume to get source-controller (and HelmRepository) able to use `oci:` then this card will need to be actioned and this logic be available in both apps?
