### ISSUE TITLE
Add Insecure item for ImageRepository 

### ISSUE THREAD

**Issue by qiuming520** [fluxcd/image-reflector-controller#313]
Add Insecure ( +optional ) item for ImageRepository 
In some cases, the secret  of docker registry is kubernetes.io/dockerconfigjson, we need set insecure is true for HTTP.
I want to add feature for ImageRepository of  Insecure ( +optional ) item

before
https://github.com/fluxcd/image-reflector-controller/blob/51caa7f2bdbd49c498b56c3e87066112f601b284/api/v1beta1/imagerepository_types.go#L34

https://github.com/fluxcd/image-reflector-controller/blob/51caa7f2bdbd49c498b56c3e87066112f601b284/controllers/imagerepository_controller.go#L216-L232

after
```
type ImageRepositorySpec struct {
	// +optional
	Insecure bool `json:"insecure,omitempty"`
       
        ...
}
```

```
func parseImageReference(url string, insecure bool) (name.Reference, error) {
	if s := strings.Split(url, "://"); len(s) > 1 {
		return nil, fmt.Errorf(".spec.image value should not start with URL scheme; remove '%s://'", s[0])
	}

	var ref name.Reference
	var err error
	if insecure {
		ref, err = name.ParseReference(url, name.Insecure)
	} else {
		ref, err = name.ParseReference(url)
	}
	
	if err != nil {
		return nil, err
	}

	imageName := strings.TrimPrefix(url, ref.Context().RegistryStr())
	if s := strings.Split(imageName, ":"); len(s) > 1 {
		return nil, fmt.Errorf(".spec.image value should not contain a tag; remove ':%s'", s[1])
	}

	return ref, nil
}

```

**Comment by aryan9600** [comment]
hi @qiuming520, thanks for opening this. this is planned and right now blocked behind a RFC: https://github.com/fluxcd/flux2/pull/3081. once the RFC gets merged, we can start work on this.
