### ISSUE TITLE
image-reflector-controller 0.40.0 breaking change gives no room for upgrading transparently 

### ISSUE THREAD

**Issue by dewe** [fluxcd/image-reflector-controller#352]
Problem: the `--aws-autologin-for-ecr` flag was deprecated and its effect removed at the same time. Now there’s no room for upgrading without breaking stuff.

Background: We have 100+ image reflections running, spread over a number of teams with their config in their own team repositories. All of these are using private AWS ECR, and we depend on the image-reflector-controller's `--aws-autologin-for-ecr` flag for authentication.

As soon as we upgrade Flux to 0.40+, the image-reflector-controller stops authenticating with ECR, and all teams’ image automations immediately stops working. Upgrading all ImageRepositories to v1beta2 would fix the problem, but it’s hard to coordinate this. 

I’d expect the image-reflector-controller to keep the flag and keep the behavior for `image.toolkit.fluxcd.io/v1beta1` API, allowing us to upgrade manifests to `v1beta2`, before removing the flag in a future release.

[Slack thread](https://cloud-native.slack.com/archives/CLAJ40HV3/p1678184516852989)

**Comment by stefanprodan** [comment]
Given that upgrading the controller also upgrades all custom resources to v1beta2 in etcd (even if in Git they are on v1beta1), I propose we use the flags to set the default for `spec.provider` (when this fields is left empty). This way, after an upgrade, all ImagePolices will keep functioning with the provider set from the flags, when uses update the policies in Git and set the provider, the flags will have no effect.
