### ISSUE TITLE
ImageRepository fails to authenticate with Gitlab Repository

### ISSUE THREAD

**Issue by daryllstrauss** [fluxcd/image-reflector-controller#360]
I'm running Flux 0.41.1 with a private project based in GitLab. I used a personal access token with privileges for the API, Repo, and Repository.
Flux is correctly managing several resources in my Git repo (so I believe the basic functionality is configured correctly), and now I am trying to get image automation pipeline going.

I created an ImageUpdateAutomation, ImagePolicy, and an  ImageRepository object that looks like this:
```yaml
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: server
  namespace: flux-system
spec:
  image: registry.gitlab.com/MYGROUPNAME/MYIMAGENAME
  interval: 1m0s
```

When this runs it never shows value in "last scan" and if I get the object from my cluster I see:

```yaml
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  annotations:
    reconcile.fluxcd.io/requestedAt: "2023-03-18T14:14:29.585045698-07:00"
  creationTimestamp: "2023-03-18T16:58:28Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 5
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: server
  namespace: flux-system
  resourceVersion: "1009332"
  uid: 52bc6c61-432d-4bc9-a3a0-4a950175cc31
spec:
  exclusionList:
  - ^.*\.sig$
  image: registry.gitlab.com/MYGROUPNAME/MYIMAGENAME
  interval: 1m0s
  provider: generic
status:
  conditions:
  - lastTransitionTime: "2023-03-19T17:54:55Z"
    message: 'scanning: first scan'
    observedGeneration: 5
    reason: ProgressingWithRetry
    status: "True"
    type: Reconciling
  - lastTransitionTime: "2023-03-18T21:14:24Z"
    message: 'scan failed: GET https://gitlab.com/jwt/auth?scope=repository%!A(MISSING)MYGROUPNAME%!F(MISSING)MYIMAGENAME%!A(MISSING)pull&service=container_registry:
      DENIED: access forbidden'
    observedGeneration: 5
    reason: ReadOperationFailed
    status: "False"
    type: Ready
  lastHandledReconcileAt: "2023-03-18T14:14:29.585045698-07:00"
  observedGeneration: -1
```

First, the message in the lastTransisionTime of the status  is corrupted.

If I unmangle that GET request, it looks like it is attempting to use the PAT to get a JWT to connect to the repository. I can do that GET request using the PAT in the flux-system secret by hand using curl, and it correctly returns the JWT. So I believe I've got the Gitlab configuration OK.

Second, I would like the scan to succeed.

**Comment by daryllstrauss** [comment]
What I expected to happen (which may well have been me misunderstanding) was that the ImageRepository would use the PAT I had created to create repository access credentials and then use those. That seems to be what happens when you have a public repository, so I mistakenly thought that's the way it worked.

You pointed out that I can use the secretRef to specify docker credentials. I have made that work.

Beyond that, I was making a mistake of trying to put the pieces of the ImageUpdateAutomation in the flux-system namespace, when it makes more sense to put it in the application's namespace. Doing that means I can re-use the same docker config credentials that I was using in the deployment. That removes the need for a duplicate copy.

I have this all working, and most the problem appears to be my misunderstanding. 

I still believe the message logged in the authentication failure, is an actual bug, but making the PAT work the way I mentioned may or may not actually be useful.

Thanks for clearing it up

**Comment by kingdonb** [comment]
It looks like the issue here is that a private repo always needs some access credential, and the message isn't very clear.

Is it ok if we close this? Thanks for using Flux! (I'm not sure what we can do about the error message, "Access Denied" is pretty much the best you can hope for when having a credential-related failure. Usually you might get 404, which would be very obscure, but Access Denied says pretty clearly what's gone wrong...)
