### ISSUE TITLE
Controller does not start on RaspberryPI (unable to open the Badger database)

### ISSUE THREAD

**Issue by bjornmagnusson** [fluxcd/image-reflector-controller#82]
Running flux (0.6.1) in a cluster using two RasberryPI. 
All but image-reflector-controller starts up fine.
Image-reflector-controller fails to allocate memory for the Badger database.

Logs:
```
kubectl -n flux-system logs image-reflector-controller-6bbbcc5c76-ttwcq
{"level":"info","ts":"2021-01-16T10:10:43.238Z","logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
badger 2021/01/16 10:10:43 INFO: All 0 tables opened in 0s
{"level":"error","ts":"2021-01-16T10:10:43.302Z","logger":"setup","msg":"unable to open the Badger database","error":"Mmap value log file. Path=/data/000000.vlog. Error=cannot allocate memory"}
```

Flux-system pods
```
kubectl get pods -n flux-system -owide
NAME                                          READY   STATUS             RESTARTS   AGE   IP           NODE   NOMINATED NODE   READINESS GATES
source-controller-bb458c944-kj76r             1/1     Running            0          15h   10.42.0.24   rpi1   <none>           <none>
helm-controller-77c9c759fb-z5f95              1/1     Running            10         15h   10.42.1.41   rpi2   <none>           <none>
notification-controller-6fbbc586b7-4kkff      1/1     Running            10         15h   10.42.1.42   rpi2   <none>           <none>
kustomize-controller-64b894fb67-8fnkq         1/1     Running            10         15h   10.42.1.44   rpi2   <none>           <none>
image-automation-controller-cd59d8b74-hh82w   1/1     Running            10         15h   10.42.1.43   rpi2   <none>           <none>
image-reflector-controller-5d98f74bc-6sxdr    0/1     CrashLoopBackOff   7647       27d   10.42.1.40   rpi2   <none>           <none>
image-reflector-controller-6bbbcc5c76-ttwcq   0/1     CrashLoopBackOff   186        15h   10.42.1.45   rpi2   <none>           <none>
```
Flux:
`flux --version
flux version 0.6.1
`

Cluster memory/cpus
```
kubectl top node
NAME   CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
rpi1   712m         17%    793Mi           81%       
rpi2   491m         12%    619Mi           63%
```

Raspberry PI details:
```
uname -a
Linux rpi1 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux
```
```
uname -a
Linux rpi2 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux
```

**Comment by stefanprodan** [comment]
Ref: https://github.com/dgraph-io/badger/issues/1229

**Comment by stefanprodan** [comment]
@bjornmagnusson can you please test the new release with:

```
kubectl -n flux-system set image deployment/image-reflector-controller manager=ghcr.io/fluxcd/image-reflector-controller:v0.3.0
```

**Comment by bjornmagnusson** [comment]
@stefanprodan Tested it just now, but unfortunately it still does not work. However there are a bit more information now.

`kubectl -n flux-system logs image-reflector-controller-d5ffcf8b7-m8mx8`
{"level":"info","ts":"2021-01-18T21:21:34.362Z","logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
badger 2021/01/18 21:21:34 INFO: All 0 tables opened in 0s
badger 2021/01/18 21:21:34 INFO: Discard stats nextEmptySlot: 0
badger 2021/01/18 21:21:34 INFO: Set nextTxnTs to 0
badger 2021/01/18 21:21:34 ERROR: Received err: Open existing file: "/data/000001.vlog" error: while opening file: /data/000001.vlog error: cannot allocate memory
while mmapping /data/000001.vlog with size: 2147483646
github.com/dgraph-io/ristretto/z.OpenMmapFileUsing
	/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.4-0.20201224172411-e860a6c48e8a/z/file.go:59
github.com/dgraph-io/ristretto/z.OpenMmapFile
	/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.4-0.20201224172411-e860a6c48e8a/z/file.go:86
github.com/dgraph-io/badger/v3.(*logFile).open
	/go/pkg/mod/github.com/dgraph-io/badger/v3@v3.0.0-20210118150219-63f09c34dec1/memtable.go:556
github.com/dgraph-io/badger/v3.(*valueLog).open
	/go/pkg/mod/github.com/dgraph-io/badger/v3@v3.0.0-20210118150219-63f09c34dec1/value.go:581
github.com/dgraph-io/badger/v3.Open
	/go/pkg/mod/github.com/dgraph-io/badger/v3@v3.0.0-20210118150219-63f09c34dec1/db.go:334
main.main
	/workspace/main.go:122
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_arm.s:857. Cleaning up...

**Comment by stefanprodan** [comment]
Ok that's helpful thanks!

So by default Badger wants 2GB of RAM, @squaremo should we should look into Badger settings and set it to 200MB?

**Comment by relu** [comment]
Or maybe even make it configurable? I see there's also an [option](https://github.com/dgraph-io/badger/issues/1229#issuecomment-591424232) to use `FILEIO` mode instead of mmap, might make sense to be able to enable that for tiny machines.

**Comment by stefanprodan** [comment]
@relu that option is gone from v3 or I haven't looked hard enough 🙃

**Comment by relu** [comment]
Indeed, it seems to be documented [here](https://github.com/dgraph-io/badger/blob/v3.2011.0/docs/content/get-started/index.md#memory-usage) and looks like it's outdated. I wasn't able to find any references related to that in the v3 codebase. Controlling the size is the only option. :man_shrugging:

**Comment by stefanprodan** [comment]
In Flux v1, the tag storage max memory is set to 512MB https://github.com/fluxcd/flux/blob/master/deploy/memcache-dep.yaml#L26 I think we should do the same here as a controller flag, I guess it would work on RasberryPI.

**Comment by squaremo** [comment]
We can certainly give a more modest allocation -- I don't know what the reasonable values are for the value log, but on the basis that it's the storage for the values, the same size as what we tend to recommend for memcached seems OK.
