### ISSUE TITLE
ImageAutomation: Custom TLS certs for container registries

### ISSUE THREAD

**Issue by bjornmagnusson** [fluxcd/image-reflector-controller#89]
For the internal Docker registry we use a TLS certificate to authenticate, instead of username/password.
The image update automation in FluxV2 lacks support for using a custom TLS certificate to authenticate towards docker registry.
In FluxV1, we used the `registry.insecureHosts` helm property as a work-around.

`flux get image repository`
```
NAME            READY   MESSAGE                                                                                 LAST SCAN       SUSPENDED
<REDACTED>        False   Get "<docker-registry-url>": x509: certificate signed by unknown authority                       False
```

`flux --version`
flux version 0.5.4

**Comment by squaremo** [comment]
@bjornmagnusson flux v1's `--registry-insecure-hosts` would try HTTPS with `TLS_INSECURE_SKIP_VERIFY`, and failing that, use HTTP. I guess you used it for that first part? Supplying a custom client and CA cert would be strictly better, because they would not bring `TLS_INSECURE_SKIP_VERIFY` along with them -- so I want to make sure that you don't need the other bits of `--registry-insecure-hosts`.

**Comment by squaremo** [comment]
Quick design:

```yaml
apiVersion: image.toolkit.fluxcd.io
kind: ImageRepository
spec:
  image: registry:8080/app-image
  interval: 5m
  certificateSecretRef:
    name: registry-certs
---
apiVersion: v1
kind: Secret
stringData:
  cacert: |
    -----BEGIN CERTIFICATE-----
    MIICojCCAYoCCQC2/92/4xw9wjANBgkqhkiG9w0BAQsFADATMREwDwYDVQQDDAhy
    ZWdpc3RyeTAeFw0yMTAxMjExNTM2NDlaFw00ODA2MDgxNTM2NDlaMBMxETAPBgNV
    BAMMCHJlZ2lzdHJ5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxYum
    DL/GWY/tKg/Mxf52opvnMGbtX41KSjjYs/IB8bqF3Y9fJWzhMiDI9+li/g2T+x5a
    YVjt1QLutZH9V3laLmRwAQBRBdCrlXV3O2fNOMGjR1Yn/l/Gix+Gts+/Uw30+hib
    reGG4bmyQBW1EkxAjqYd6HYELPD+/wV/lVl1jylkipr8Rs5e4nABZZ4Yk0y+2JUg
    Qbf7wECux5aGsQKyiqa5gPDNWd2suAfekqmhi+iO+4L8/IgXM7vytbXrYbVnMVQ7
    /tm/Vibwabb3ZJ8A0vU6g9ZbpXphRd3gdL+mDM02NhDBr/8VaMufLb9kWsjtBW9q
    WFYMDiB3zordJRQwoQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQCk0yKYEmTEd/9T
    tP0Lgtzn96iVrmLgUY6x+a00m+vHpMYioGxzwjbLQ2CFr3FcgE3mlm7z9+A9wg7t
    cq+QU0tqDHWyLmhvars6aXcZp+RJV0oRv2uBWqw41amQGX17Bltx6j8FeaOP4Pfp
    PxrUH0l290ixgl22QbuGHMxiKh3+D5dtWOr2M/3d+bfwQU7yxkSN7O7wTHZFIVGP
    bHpMqQbmFRgA+G0ihQjsiZpnn2mQE44Y5hAqCI73c9ncmP9VTGDtL5kx8iepjoSV
    3XulBJXDuJ1gTNqX5pDOO9wvh30CB+WHoNH6gRoxa5X10TKVMDkhEyGosR1Hp4rX
    k2vUMz8m
    -----END CERTIFICATE-----
  clientcert: |
    -----BEGIN CERTIFICATE-----
    TOTALLYDIFFERENT9wjANBgkqhkiG9w0BAQsFADMREwDwYDVQQDDAhy
    ZWdpc3RyeTAeFw0yMTAxMjExNTM2NDlaFw00ODA2MDgxNTM2NDlaMBMxETAPBgNV
    BAMMCHJlZ2lzdHJ5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxYum
    DL/GWY/tKg/Mxf52opvnMGbtX41KSjjYs/IB8bqF3Y9fJWzhMiDI9+li/g2T+x5a
    YVjt1QLutZH9V3laLmRwAQBRBdCrlXV3O2fNOMGjR1Yn/l/Gix+Gts+/Uw30+hib
    reGG4bmyQBW1EkxAjqYd6HYELPD+/wV/lVl1jylkipr8Rs5e4nABZZ4Yk0y+2JUg
    Qbf7wECux5aGsQKyiqa5gPDNWd2suAfekqmhi+iO+4L8/IgXM7vytbXrYbVnMVQ7
    /tm/Vibwabb3ZJ8A0vU6g9ZbpXphRd3gdL+mDM02NhDBr/8VaMufLb9kWsjtBW9q
    WFYMDiB3zordJRQwoQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQCk0yKYEmTEd/9T
    tP0Lgtzn96iVrmLgUY6x+a00m+vHpMYioGxzwjbLQ2CFr3FcgE3mlm7z9+A9wg7t
    cq+QU0tqDHWyLmhvars6aXcZp+RJV0oRv2uBWqw41amQGX17Bltx6j8FeaOP4Pfp
    PxrUH0l290ixgl22QbuGHMxiKh3+D5dtWOr2M/3d+bfwQU7yxkSN7O7wTHZFIVGP
    bHpMqQbmFRgA+G0ihQjsiZpnn2mQE44Y5hAqCI73c9ncmP9VTGDtL5kx8iepjoSV
    3XulBJXDuJ1gTNqX5pDOO9wvh30CB+WHoNH6gRoxa5X10TKVMDkhEyGosR1Hp4rX
    k2vUMz8m
    -----END CERTIFICATE-----
```

An alternative would be to look for the certs in the secret referred to with `secretRef`; however, those are often generated with `kubectl create secret docker-regsitry ...`, and with automation, and either of those makes it inconvenient to include certificates. You can always name the same secret, if you put the certificates there.

When a certificate secret is includes, the controller will look for those two fields, parse and use which of them is present for HTTPS requests. So you could include a CA certificate if you want to use TLS but don't need to authenticate with a client certificate; or, you could use a client certificate if you _are_ authenticating with the certificate, but your server has a fancy CA-signed certificate itself.

**Comment by stefanprodan** [comment]
We could use a shorter fielded name like `certSecretRef`.

**Comment by stefanprodan** [comment]
@squaremo I would consider using the same key names we currently use for HelmRepositories https://toolkit.fluxcd.io/components/source/helmrepositories/#spec-examples

```
apiVersion: v1
kind: Secret
type: Opaque
data:
  certFile: <BASE64>
  keyFile:  <BASE64>
  caFile:   <BASE64>
```

**Comment by squaremo** [comment]
> I would consider using the same key names we currently use for HelmRepositories

Does HelmRepository eschew the format used by `kubectl create secret tls` for the same reason I initially did? (to wit: I didn't know about it)

**Comment by stefanprodan** [comment]
Those keys names are part of the Helm API used for defining the `repositories.yaml`, I think this API predates `kubectl create secret tls`.

**Comment by squaremo** [comment]
> Those keys names are part of the Helm API used for defining the `repositories.yaml`, I think this API predates `kubectl create secret tls`.

Got it, they are from a parallel tradition :-) I guess I could look for either set of keys; I don't _expect_ people to be creating secrets for this in the same way they'd create them for Helm; but it might avoid some surprises, so why not.

**Comment by stefanprodan** [comment]
As with Git and Helm we will provide a `flux create secret tls` command that will generate a secret with certFile, keyFile and caFile keys. We already do that for Helm so adding the `tls` command should take 5 minutes of copy/paste :))

**Comment by stefanprodan** [comment]
@squaremo if we standardise around `kubernetes.io/tls` for `ImageRepository` then how should we go about `GitRepository`  https://github.com/fluxcd/source-controller/issues/93? Should we introduce a separate `certSecretRef` field there too?

**Comment by squaremo** [comment]
There's problems either way around:
 - a) secrets created with `kubectl create secret tls` don't have a ca cert -- you would have to add that yourself if you need it
 - b) the secrets for Helm etc. include username/password, which isn't necessary here since those are expected to come from an imagePullSecret

I think it makes more sense for Git and Helm to use their own format. Image repos are a special case because they use imagePullSecrets -- but because of a) above, I'm going to expect the Git/Helm format for certs, and support TLS secrets as a convenience only.

**Comment by stefanprodan** [comment]
You're right, both Helm and Git-over-https include username/password. 

> I'm going to expect the Git/Helm format for certs, and support TLS secrets as a convenience only.

Sounds great, thank you.

**Comment by bjornmagnusson** [comment]
Looks promising. 
I wonder if there is any possibility that this kind of configuration can be done on a global level for the entire cluster? (as it applies to all automations in that cluster).

**Comment by bjornmagnusson** [comment]
Let me know when there is an version of image-reflector-controller to try out, and I will be happy to do it in our context.

**Comment by squaremo** [comment]
@bjornmagnusson This issue got automagically closed because I mentioned it in the pull request; the TLS certs bit of API should make its way into the next release, which will surely be soon!

**Comment by squaremo** [comment]
> I'm going to expect the Git/Helm format for certs, and support TLS secrets as a convenience only.

In the end I just implemented secrets with the `flux create secret` data keys (and see https://github.com/fluxcd/flux2/pull/788).

I could add `kubectl create secret tls` support in another PR. What do you think @bjornmagnusson, would you expect to be able to use `kubectl create secret tls`?
